apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service-load-balancer-service
spec:
  selector:
    component: movie-catalog-service-pod
  ports: 
    - name: http
      port: 80
      targetPort: 8081 
  type: LoadBalancer # Essa conf faz com que um novo LoadBalancer seja aprovisionado e configurado na AWS
