kind: Secret
apiVersion: v1
metadata:
  name: movie-catalog-service-secret
type: Opaque
data:
  username: TUNJREE=
  password: eDEyMzQ=
  # base64 do user e pass (criado via .htpasswd) que sera utilizado no basic auth do ingress
  auth: QVBQX09BR19NT1ZJRUNBVEFMT0dfTVM6JGFwcjEkaEJBTEFRam0kYmtrQ2FKL0RjTVVMdnkueFFmY0xZMAo=
