apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  author: "Dhiego Duarte"
  email: "dhiego.duarte.terceiros@claro.com.br"
  company: "Claro BR"
  revision: "${GIT_COMMIT_FORMATTED}" # replaced during jenkins pipeline 
resources:
- ./movie-catalog-service-sidecar-fatura-net-esb-legado-relacionar-endpoint.yaml