kind: ConfigMap
apiVersion: v1
metadata:
  name: movie-catalog-service-config-map
data:
  # Simulando uma conf para host de banco de dados
  db-host: database_hostname
  # hostname and port for ratings-data-service microservice
  ratings-data-service-hostname: ratings-data-service-cluster-ip-service
  ratings-data-service-port: '8083'
  # hostname and port for movie-info-service microservice
  movie-info-service-hostname: movie-info-service-cluster-ip-service
  movie-info-service-port: '8082'
  # hostname and port for movie-catalog-service-sidecar-fatura
  movie-catalog-service-sidecar-fatura-hostname: localhost # always use localhost for sidecar containers
  movie-catalog-service-sidecar-fatura-port: '8084'
  application.yaml: |-
    # Actuator configurations https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready
    management.endpoints.web.exposure.include: '*'
    management.endpoints.web.exposure.exclude: refresh,restart,pause,resume
    management.endpoint.health.show-details: always #never always
    # Enabling for /actuator/health endpoint
    management.health.circuitbreakers.enabled: true
    management.health.ratelimiters.enabled: true
    # resilience4j configurations http://resilience4j.github.io/resilience4j/#_spring_boot_2_starter
    resilience4j.circuitbreaker:
        backends:
            ratings-data-service-circuitbreaker:
                registerHealthIndicator: true
                # The Ring Bit Buffer must be full, before the failure rate can be calculated. For example, if the size of the Ring Buffer is 10, then at least 10 calls must evaluated, before the failure rate can be calculated 
                ringBufferSizeInClosedState: 5 # the size of the ring buffer when the CircuitBreaker is closed
                ringBufferSizeInHalfOpenState: 3 # the size of the ring buffer when the CircuitBreaker is half open
                waitDurationInOpenState: 5000 # the wait duration which specifies how long the CircuitBreaker should stay open, before it switches to half open
                failureRateThreshold: 10 # the failure rate threshold in percentage above which the CircuitBreaker should trip open and start short-circuiting calls
                eventConsumerBufferSize: 10 # The size of a event consumer buffer can be configured per CircuitBreaker
                #ignoreExceptions: #  list of exceptions which should be ignored and not increase failure count
                    #- io.github.robwin.exception.BusinessException
                #recordExceptions: # a list of exceptions which should increase failure count
                    #- java.util.concurrent.TimeoutException  
            movie-info-service-circuitbreaker:
                registerHealthIndicator: true
                # The Ring Bit Buffer must be full, before the failure rate can be calculated. For example, if the size of the Ring Buffer is 10, then at least 10 calls must evaluated, before the failure rate can be calculated 
                ringBufferSizeInClosedState: 5 # the size of the ring buffer when the CircuitBreaker is closed
                ringBufferSizeInHalfOpenState: 3 # the size of the ring buffer when the CircuitBreaker is half open
                waitDurationInOpenState: 5000 # the wait duration which specifies how long the CircuitBreaker should stay open, before it switches to half open
                failureRateThreshold: 50 # the failure rate threshold in percentage above which the CircuitBreaker should trip open and start short-circuiting calls
                eventConsumerBufferSize: 10 # The size of a event consumer buffer can be configured per CircuitBreaker
                #ignoreExceptions: #  list of exceptions which should be ignored and not increase failure count
                    #- io.github.robwin.exception.BusinessException
                #recordExceptions: # a list of exceptions which should increase failure count
                    #- java.util.concurrent.TimeoutException  
    resilience4j.retry:
        backends:
            ratings-data-service-retry:
                maxRetryAttempts: 1
                waitDuration: 100
                #retryExceptions:
                #    - org.springframework.web.client.HttpServerErrorException
                #ignoreExceptions:
                #    - io.github.robwin.exception.BusinessException
            movie-info-service-retry:
                maxRetryAttempts: 1
                waitDuration: 100
                #retryExceptions:
                #    - org.springframework.web.client.HttpServerErrorException
                #ignoreExceptions:
                #    - io.github.robwin.exception.BusinessException
    resilience4j.bulkhead:
        backends:
            ratings-data-service-bulkhead:
                maxConcurrentCall: 10 # max amount of parallel executions allowed by the bulkhead
            movie-info-service-bulkhead:
                maxConcurrentCall: 10 # max amount of parallel executions allowed by the bulkhead
    resilience4j.ratelimiter:
        limiters:
            ratings-data-service-ratelimiter:
                registerHealthIndicator: true
                limit-refresh-period-in-millis: 1 # the period of limit refresh, after each period rate limiter sets its permissions count to limitForPeriod value
                limit-for-period: 10 # the permissions limit for refresh period
                timeout-in-millis: 25 # the default wait for permission duration
            movie-info-service-ratelimiter:
                registerHealthIndicator: true
                limit-refresh-period-in-millis: 1 # the period of limit refresh, after each period rate limiter sets its permissions count to limitForPeriod value
                limit-for-period: 10 # the permissions limit for refresh period
                timeout-in-millis: 25 # the default wait for permission duration